env:
  browser: true
  es6: true
extends: google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  allowImportExportEverywhere: true
plugins:
  - react
rules: {
  react/jsx-uses-vars: ["error"],
  require-jsdoc: ["error", {
    "require": {
      "FunctionDeclaration": false,
      "MethodDefinition": false,
      "ClassDeclaration": false,
      "ArrowFunctionExpression": false,
      "FunctionExpression": false
    }}
  ],
  object-curly-spacing: [2, "always"]
}
