env:
  browser: true
  es2022: true
extends: google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2022
  sourceType: module
  allowImportExportEverywhere: true
plugins:
  - react
rules:
  {
    arrow-parens: [ "error", "as-needed", { "requireForBlockBody": true } ],
    indent: [ "error", "tab", { "SwitchCase": 1 } ],
    max-len: [ "error", { "code": 120 } ],
    object-curly-spacing: [ "error", "always" ],
    no-mixed-spaces-and-tabs: [ "error", "smart-tabs" ],
    no-tabs: [ "error", { allowIndentationTabs: true } ],
    react/jsx-uses-vars: [ "error" ],
    require-jsdoc:
      [
        "error",
        {
          "require":
            {
              "FunctionDeclaration": false,
              "MethodDefinition": false,
              "ClassDeclaration": false,
              "ArrowFunctionExpression": false,
              "FunctionExpression": false,
            },
        },
      ],
  }
