apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main
  namespace: {{.KUBE_NAMESPACE}}
  labels:
    app: main
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: letsencrypt
spec:
  rules:
  - host: harmelodic.com
    http:
      paths:
        - path: /
          backend:
            serviceName: main
            servicePort: 80
  - host: "*.harmelodic.com"
    http:
      paths:
        - path: /
          backend:
            serviceName: main
            servicePort: 80
  tls:
  - hosts:
    - "*.harmelodic.com"
    - harmelodic.com
    secretName: tls-cert-wildcard-harmelodic-com
