apiVersion: v1
kind: Service
metadata:
  name: main
  labels:
    app: main
spec:
  ports:
  - name:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: main
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}