name: master
on:
  push:
    branches:
      - master
jobs:
  npm-test:
    runs-on: ubuntu-latest
    container: node:17
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm i
          npm test

  npm-build:
    needs:
      - npm-test
    runs-on: ubuntu-latest
    container: node:17
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm i
          npm run build

#  docker-gcp:
#    needs:
#      - npm-build
#    runs-on: ubuntu-latest
#    container: docker:latest
#    services:
#      dind:
#        image: docker:dind
#    steps:
#      - with:
#          path: public/*
#        run: |
#          echo $GCP_SERVICE_KEY | docker login -u _json_key --password-stdin https://gcr.io
#          docker build -t "${GCP_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
#          docker tag "${GCP_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${GCP_REGISTRY_IMAGE}:latest"
#          docker push "${GCP_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
#          docker push "${GCP_REGISTRY_IMAGE}:latest"
